baseURL = "https://karthiktiwari.vercel.app"  # or your custom domain
languageCode = "en-US"
title = "Karthik Tiwari"
theme = "hugo-bearblog"
author = "Karthik Tiwari"
copyright = "Copyright © 2025, Karthik Tiwari."
enableRobotsTXT = true

# Disable taxonomy pages (tags/categories) if unused
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

# Permalinks — this ensures /posts/my-blog-post/ URLs
[permalinks]
  posts = "/posts/:slug/"

[params]
  description = "AI Engineer. Systems Builder. Creative Technologist."
  favicon = "images/favicon.png"
  images = ["images/share.png"]
  title = "Karthik Tiwari"
  # hideMadeWithLine = true  # Uncomment to remove footer attribution
  # dateFormat = "2006-01-02"  # Optional: ISO date format

[markup]
  [markup.highlight]
    style = "friendly"
    lineNos = true
    lineNumbersInTable = false
    codeFences = true
