baseURL = "https://karthiktiwari.vercel.app"
languageCode = "en-US"
title = "Karthik Tiwari"
theme = "hugo-bearblog"
author = "Karthik Tiwari"
copyright = "Copyright © 2025, Karthik Tiwari."
enableRobotsTXT = true

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[permalinks]
  posts = "/posts/:slug/"

[params]
  description = "AI Engineer. Systems Builder. Creative Technologist."
  favicon = "images/favicon.png"
  images = ["images/share.png"]
  title = "Karthik Tiwari"
  # hideMadeWithLine = true
  # dateFormat = "2006-01-02"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 3

[markup]
  [markup.highlight]
    style = "friendly"
    lineNos = true
    lineNumbersInTable = false
    codeFences = true
