baseURL = "https://karthiktiwari.vercel.app/" # Replace with your domain
languageCode = "en-us"
title = "Karthik Tiwari"
theme = "hugo-bearblog"

[params]
  description = "Engineer. Builder. AI Explorer."
  author = "Karthik Tiwari"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 3
